define 

    #ATTRIBUTES 

    name sub attribute,
        value string;

    title sub attribute,
        value string;

    phone sub attribute,
        value string;

    gender sub attribute,
        value string;

    email sub attribute,
        value string;

    account-number sub attribute,
        value string;

    account-balance sub attribute,
        value long;

    product-name sub attribute,
        value string; 

    ID sub attribute,
        value long;

    #ENTITIES 

    customer sub entity,
        owns ID @key,
        owns name,
        owns title, 
        owns phone, 
        owns gender, 
        owns email,
        plays ownership:account-owner;

    bank-details sub entity, 
        owns ID @key, 
        owns account-balance, 
        owns product-name,
        plays ownership:account;

    #RELATIONS 
    
    ownership sub relation, 
        owns ID @key,
        relates account-owner,
        relates account;



